# Generated by Django 4.1 on 2022-10-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='stats',
            field=models.CharField(max_length=50),
        ),
    ]
